swipe:
  4:
    down:
      sendkey: "LEFTMETA+o"
      # command: 'xdotool key super+o'
    up: 
      sendkey: "LEFTMETA+p"
      # command: 'xdotool key super+p'
  3:
    # Switching Desktops
    up: 
      sendkey: "LEFTMETA+down"
      # command: 'xdotool key super+Down'
    left:
      sendkey: "LEFTMETA+left"
      # command: 'xdotool key super+Left'
    right:
      sendkey: "LEFTMETA+right"
      # command: 'xdotool key super+Right'
    down: 
      sendkey: "LEFTMETA+up"
      # command: 'xdotool key super+Up'


pinch:
  # 2:
  #   in:
  #     command: 'xdotool keydown ctrl click 4 keyup ctrl' # Zoom in
  #   out:
  #     command: 'xdotool keydown ctrl click 5 keyup ctrl' # Zoom out
  3:
    out:
      command: 'xdotool key Escape'



plugin:
  inputs:
    libinput_command_input:
      enable-tap: true
      enable-dwt: true
      show-keycodes: true

