swipe:
  2:
    # going forwards and back in browser, dolphin, etc
    right:
      sendkey: "LEFTALT+right"
    left: 
      sendkey: "LEFTALT+left"
  3:
    # Switching Desktops
    up: 
      sendkey: "LEFTMETA+down"
      # command: 'xdotool key super+Down'
    left:
      sendkey: "LEFTMETA+left"
      # command: 'xdotool key super+Left'
    right:
      sendkey: "LEFTMETA+right"
      # command: 'xdotool key super+Right'
    down: 
      sendkey: "LEFTMETA+up"
      # command: 'xdotool key super+Up'
  4:
    right:
      sendkey: "LEFTMETA+o"
      # command: 'xdotool key super+o'
    left: 
      sendkey: "LEFTMETA+p"
      # command: 'xdotool key super+p'
    up: 
      sendkey: "esc"
    down: 
      command: 'krunner'




plugin:
  inputs:
    libinput_command_input:
      enable-tap: true
      enable-dwt: true
      show-keycodes: true

