swipe:
  3:
    # Switching Desktops
    up: 
      sendkey: "LEFTMETA+down"
    left:
      sendkey: "LEFTMETA+right"
    right:
      sendkey: "LEFTMETA+left"
    down: 
      sendkey: "LEFTMETA+up"
  4:
    right:
      sendkey: "LEFTMETA+o" # on my system this is overview
    left: 
      sendkey: "LEFTMETA+p" # on my system this is present windows
    down:
      sendkey: ESC
    # up: # 
    #   sendkey: "LEFTALT+LEFTSHIFT+d"  # on my system this is present desktops

# hold:
#   4:
#     command: 'krunner'

rotate: # Easier gesture to do with one hand than pinching
  2:
    clockwise:
      sendkey: 'LEFTALT+SPACE' # on my system this is krunner
    counterclockwise:
      sendkey: ESC





plugin:
  inputs:
    libinput_command_input:
      enable-tap: true
      enable-dwt: true
      show-keycodes: true

